services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py collectstatic --noinput && gunicorn project_settings.wsgi:application --workers 1 --threads 2 --timeout 120